<?php

namespace Magecore\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function findAllByProjectId($id)
    {
        $em = $this->getEntityManager();

        $rep = $em->createQueryBuilder()
            ->select('a')
            ->from('MagecoreTestTaskBundle:Activity', 'a')
            ->innerJoin('a.issue', 'MagecoreTestTaskBundle:Issue', 'i')
            ->where('MagecoreTestTaskBundle:Issue.project = :pro')
            ->setParameter('pro', $id);




        return $rep->getQuery()
            ->getResult();
    }

    /**
     * @param $id
     * @return array
     */
    public function findAllByUserMemberId($id)
    {
        $em = $this->getEntityManager();

        $rep = $em->createQueryBuilder()
            ->select('a')
            ->from('MagecoreTestTaskBundle:Activity', 'a')
            ->innerJoin('a.user', 'u', 'WITH', 'u.id = :id')
            ->innerJoin('a.issue', 'i')
            ->innerJoin('i.project', 'p')
            ->innerJoin('p.members', 'm', 'WITH', 'm.id=u.id')
            ->setParameter('id', $id);




        return $rep->getQuery()
            ->getResult();
    }

}
