<?php

namespace Magecore\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findAllByProjectId($id)
    {
        $em = $this->getEntityManager();

        $rep = $em->createQueryBuilder()
            ->select('a')
            ->from('MagecoreTestTaskBundle:Activity','a')
            ->innerJoin('a.issue', 'MagecoreTestTaskBundle:Issue','i')
            ->where('MagecoreTestTaskBundle:Issue.project = :pro')
            ->setParameter('pro',$id);




        return $rep->getQuery()
            ->getResult();
    }
}
