<?php
/**
 * Created by PhpStorm.
 * User: jude
 * Date: 30.06.15
 * Time: 12:58
 */

namespace Magecore\Bundle\TestTaskBundle\Twig;

use Magecore\Bundle\TestTaskBundle\Entity\Comment;
use Magecore\Bundle\TestTaskBundle\Entity\Issue;
use Magecore\Bundle\TestTaskBundle\Entity\Project;
use Magecore\Bundle\TestTaskBundle\Entity\User;
use Magecore\Bundle\TestTaskBundle\Helper\FileManagerHelper;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Security\Core\SecurityContext;

class AppExtension extends \Twig_Extension
{
    protected $context;

    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('datertz', array($this, 'datertzFilter')),
            new \Twig_SimpleFilter('showPath', array($this, 'avaPathFilter')),
        );
    }

    public function getGlobals()
    {
        return
            //parent::getGlobals(); // TODO: Change the autogenerated stub
        array( 'route_helper' => '@my.helper'
                );
    }

    protected function getCurrentUser()
    {
        return $this->context->getToken()->getUser();

    }


    public function datertzFilter(\DateTime $date)
    {
        $user= $this->getCurrentUser();
        $tz = $user->getTimezone();
        $date->setTimezone(new \DateTimeZone($tz));
        return $date->format('Y.m.d H:i:s');
    }

    public function avaPathFilter($avapath)
    {
        return $this->filemanager->getWebPath($avapath);
    }

    public function __construct(ContainerInterface $container, SecurityContext $context, FileManagerHelper $fileManager)
    {
        $this->context = $context;
        $this->filemanager = $fileManager;
    }

    public function getName()
    {
        return 'app_extension';
    }
}