imports:
    - { resource: config_dev.yml }

parameters:
    locale: fr

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
#    translator:      { fallbacks: ["fr"] }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        secured_area:
            http_basic: ~
